config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :users, only: :show
  resources :animes, only: [ :index, :show ] do
    resources :theory, only: :create
    resources :reviews, only: :create
    resources :watchlist_animes, only: [ :create, :index ]
  end
  resources :watchlist_animes, only: :destroy
  resources :reviews, only: [ :update, :destroy ]
end

app/models/anime.rb
class Anime < ApplicationRecord
	has_many :reviews, dependent: :destroy
  has_many :watchlist_animes, dependent: :destroy
  has_many :theories, dependent: :destroy
  has_one_attached :photo

  def blank_stars
    5 - rating.to_i
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :anime
  belongs_to :user
end

app/models/theory.rb
class Theory < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reviews, dependent: :destroy
  has_many :theories, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :watchlist_animes, dependent: :destroy
  has_many :animes, through: :watchlist_animes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
  belongs_to :user
  belongs_to :anime
end

app/models/watchlist_anime.rb
class WatchlistAnime < ApplicationRecord
  belongs_to :user
  belongs_to :anime

  validates :anime, uniqueness: { scope: :user }
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def index
    if params[:query].present?
      @animes = Anime.where("title ILIKE ?", "%#{params[:query]}%")
    elsif params[:category].present?
      @animes = Anime.where(category: params[:category])
    elsif params[:streaming_service].present?
      @animes = Anime.where(streaming_service: params[:streaming_service])
    else
      @animes = Anime.all
    end
  end
  
  def show
    @anime = Anime.find(params[:id])
    if current_user != nil
      @watchlist = current_user.watchlist_animes.find_by(anime: @anime)
    end
    @review = Review.new
  end
  
  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      redirect_to animes_path(current_user)
    else
      render :new
    end
  end

  private

  def anime_params
    params.require(:anime).permit(:title, :description, :parution_date, :category, :streaming_service, :rating, :photo)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @animes = Anime.all

    unfiltered_categories = @animes.map { |anime| anime.category } 
    @categories = unfiltered_categories.uniq

    unfiltered_streaming_services = @animes.map { |anime| anime.streaming_service } 
    @streaming_services = unfiltered_streaming_services.uniq
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_review, only: [ :update, :destroy ]

  def create
    @anime = Anime.find(params[:anime_id])
    @review = Review.new(review_params)
    @review.user = current_user
    if @review.save
      redirect_to user_path(current_user)
    else
      render :new
    end
  end

  def update
    @review.update(review_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @review.destroy
    redirect_to user_path(current_user)
  end

  private

  def find_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/theories_controller.rb
class TheoriesController < ApplicationController
  def create
    @theory = Theory.new(theory_params)
    @theory.user = current_user
    if @theory.save
      redirect_to user_path(current_user)
    else
      render "animes/show"
    end
  end
  
  private

  def theory_params
    params.require(:theory).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
    @watchlist = current_user.watchlist_animes
  end
end

app/controllers/watchlist_animes_controller.rb
class WatchlistAnimesController < ApplicationController

  def index
    @watchlist_animes = WatchlistAnime.all
  end
  
  def create
    @anime = Anime.find(params[:anime_id])
    if current_user.nil?
      redirect_to anime_path(@anime), notice: "Vous devez vous connecter"
    else
      @watchlist_animes = WatchlistAnime.new(user_id: current_user.id, anime_id: @anime.id)
      if @watchlist_animes.save
        redirect_back(fallback_location: root_path, notice: "Anime ajouté de votre Watchlist")
      else
        redirect_to animes_path
      end
    end
  end

  def destroy
    @watchlist_anime = WatchlistAnime.find(params[:id])
    @watchlist_anime.destroy
    redirect_back(fallback_location: root_path, notice: "Anime supprimé de votre Watchlist")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo_streaming_service(streaming_service)
    case streaming_service 
    when "Wakanim"
      image_tag('wakanim_logo.png', class: "wakanim-logo")
    when "Netflix"
      image_tag('netflix_logo.png', class: "netflix-logo")
    when "Crunchyroll"
      image_tag('crunchyroll_logo.png', class: "crunchyroll-logo")
    when "ADN"
      image_tag('adn_logo.png', class: "adn-logo")
    end
  end
end

app/views/animes/index.html.erb
<div class="container mt-5 body-size">
  <div class="top-index">
    <div class="search-result">
      <% if params[:query].present? %>
        <h4>Résultat de la recherche : "<%= params[:query] %>"</h4>
      <% elsif  params[:category].present? %>
        <h4>Tous les animés dans la catégorie : "<%= params[:category] %>"</h4>
      <% elsif  params[:streaming_service].present? %>
        <h4>Tous les animés disponibles sur : "<%= params[:streaming_service] %>"</h4>
      <% else %>
        <h4>Tous les animés</h4>
      <% end %>
      <p class="count_result"><%= @animes.count %> résultats</p>
    </div>

    <div class="search-index">
      <%= form_tag animes_path, method: :get do %>
        <%= text_field_tag :query,
        params[:query],
        class: "searchTerm",
        placeholder: "Recherchez..."
        %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <% @animes.each do |anime| %>
      <div class="card m-4">
        <a href="<%= anime_path(anime) %>">
          <div class="cards-img-container">
            <%= cl_image_tag anime.photo.key, class: "card-img" %>
          </div>
          <div class="card-description">
            <h1 class="title-card"><%= anime.title %></h1>
          </a>
          <div class="like-btn">
            <% if current_user != nil %>
              <% if anime.in?(current_user.animes) %>
                <%= link_to watchlist_anime_path(WatchlistAnime.where(user_id: current_user.id, anime_id: anime.id).first), method: :delete, remote: true do%>
                  <div class="like" data-like-state="1"></div>
                <% end %>
              <% else %>
                <%= link_to anime_watchlist_animes_path(anime), method: :post, remote: true do%>
                  <div class="like" data-like-state="0"></div>
                <% end %>
              <% end %>
            <% end %>
          </div>
          <p class="category"><%= anime.category %></p>
          <p class="rating">
            <% anime.rating.times do  %>
              <i class="fas fa-star"></i>
            <% end %>
            <% anime.blank_stars.times do %>
              <i class="far fa-star"></i>
            <% end %>
            (<%= anime.vote %> votes)
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/animes/show.html.erb
<body class="show_body"></body>
<div class="anime-show-container">
  <div class="image-anime-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @anime.photo.key, crop: :fill %>')">
  </div>
  <div class="anime-description-streaming-show">
    <div class="anime-info-show">
      <div class="anime-title-like-heart-show">
        <h1 class="anime-title-show font-family-title"><%= @anime.title %></h1>
        <div class="like-btn-show">
          <% if current_user != nil %>
            <% if @anime.in?(current_user.animes) %>
              <%= link_to watchlist_anime_path(@watchlist), method: :delete do%>
                <div class="like" data-like-state="1"></div>
              <% end %>
            <% else %>
              <%= link_to anime_watchlist_animes_path(@anime), method: :post do %>
                <div class="like" data-like-state="0"></div>
              <% end %>
            <% end %>
          <% end %>
        </div>        
      </div>
      <p class="description_anime_show"><%= @anime.description %></p>
      <div class="anime-date-genre-note-show">
        <div class="note-globale-show-anime">
          <p class="title-colored mb-0">Note globale</p>
          <p class="rating">
            <% @anime.rating.times do  %>
              <i class="fas fa-star"></i>
            <% end %>
            <% @anime.blank_stars.times do %>
              <i class="far fa-star"></i>
            <% end %>
          </p>
        </div>
        <div class="date-show-anime">
          <p class="title-colored mb-0">Date de diffusion</p>
          <p><%= @anime.parution_date %></p>
        </div>
        <div class="genre-show-anime">
          <p class="title-colored mb-0">Genre</p>
          <p><%= @anime.category %></p>
        </div>
      </div>
    </div>
    <div class="plateform-show-anime">
      <h2 class="anime-title-show dispo-on">Disponible sur:</h2>
      <p class="d-inline"><%= logo_streaming_service(@anime.streaming_service) %>
        <%= link_to "https://www.crunchyroll.com/fr/jujutsu-kaisen", target:"_blank" do %>
          <p class="btn btn-light ml-4 btn-lg"><span class="text-dark">Visionner <i class="fas fa-play ml-2"></i></span></p>
        <% end %>
      </p>
    </div>
  </div>
</div>
<div class="pred">
  <div class="commentary-prediction-anime-show">
    <h1 class="title_prediction mb-4">Théories</h1>
    <div class="card-product">
      <%= image_tag 'joseph.jpg' %>
      <div class="card-product-infos">
        <div class="card_user_info mr-5">
          <h2>Joseph <span class="date_card_theory"> (20/03/2021)</span> <span class="rank_font ml-2" id="rank_theory">Apprenti </span></h2>
          <p>Les fléaux vont sceller Gojo c’est sur !</p>
        </div>
        <div class="upvote ml-5">
          <p class="button" id="minus">-</p>
          <p id="count">99</p>
          <p class="button" id="plus">+</p>
        </div>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag 'thomas.png' %>
      <div class="card-product-infos">
        <div class="card_user_info mr-5">
          <h2>Thomas<span class="date_card_theory"> (21/03/2021)</span><span class="rank_font ml-2">Apprenti</span></h2>
          <p>A tous les coups, Yuji va surpasser Todo dans le prochain épisode.</p>
        </div>
        <div class="upvote ml-5">
          <p class="button" id="minus">-</p>
          <p id="count">6</p>
          <p class="button" id="plus">+</p>
        </div>
      </div>
    </div>
    <div class="card-product">
      <%= image_tag 'fabien.png' %>
      <div class="card-product-infos">
        <div class="card_user_info mr-5">
          <h2>Fabien<span class="date_card_theory"> (26/03/2021)</span><span class="rank_font ml-2">Apprenti</span></h2>
          <p><span class="text-primary">@Thomas</span> Hum je ne suis pas sûr, Todo est toujours au dessus avec sa technique de transfert !</p>
        </div>
        <div class="upvote ml-5">
          <p class="button" id="minus">-</p>
          <p id="count">27</p>
          <p class="button" id="plus">+</p>
        </div>
      </div>
    </div>
    <%# ------------------------------------------------------- %>
    <div id="quentin_comments" class="card-product">
      <%= image_tag 'quentin.png' %>
      <div class="card-product-infos">
        <div class="card_user_info mr-5">
          <h2>Quentin<span class="date_card_theory"> (27/03/2021)</span><span class="rank_font ml-2">Apprenti</span></h2>
          <p><span class="text-primary">@Joseph</span> t'es un genie</p>
        </div>
        <div class="upvote ml-5">
          <p class="button" id="minus">-</p>
          <p id="count">0</p>
          <p class="button" id="plus">+</p>
        </div>
      </div>
    </div>
    <%# ------------------------------------------------------- %>
    <div class="d-flex flex-row w-100 mt-3">
      <input class="w-100" type="text" placeholder="Partagez votre théorie">
      <div id="fake_post" class="btn btn-dark">Envoyer</div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Japanimes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%# <div class="body-height">
    </div> %>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
        
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<%= render 'shared/carousel' %>

<div class="vod">
  <h3>Choisissez en fonction de vos abonnements</h3>
  <div class="vod-choice">
    <% @streaming_services.each do |streaming_service| %> 
      <%= link_to animes_path(streaming_service: streaming_service) do %>
        <%= logo_streaming_service(streaming_service) %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="category">
  <h3>Recherchez par genre</h3>
  <ul class="category-choice">
    <li>
      <% @categories.each do |category| %>
        <span class="button-3d">
          <%= link_to "#{category}", animes_path(category: category), class: 'remove-deco' %>
        </span>
      <% end %>
    </li>
  </ul>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)), url(<%= image_path "cross_banner.png" %>); background-size: cover;">
  <div class="tagline">
    <div class="Tagline-item search-tagline">
      <h1>Recherchez</h1>
      <p>Que vous soyez incollable ou néophyte, trouvez sans peine vos prochaines aventures !</p>
    </div>
    <div class="Tagline-item watch-tagline">
      <h1>Regardez</h1>
      <p>Rejoignez facilement les plateformes VOD pour visionner vos sélections.</p>
    </div>
    <div class="Tagline-item theory-tagline">
      <h1>Théorisez</h1>
      <p>Prolongez l'expérience et partager vos pronostics.</br>
      Serez-vous le prochain maître des prophéties ?!</p>
    </div>
  </div>
  <div class="search-home">
    <%= render 'shared/searchbar', animes: @animes %>
  </div>
</div>

app/views/shared/_carousel.html.erb
<div class="home_container">
  <h2>Indécis ? Laissez-nous vous inspirer !</h2>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
    </ol>
    <div class="carousel-inner">
      <div class="text-anim-top"><p>ANIMES DU MOMENT</p></div>
      <div class="carousel-item">
        <%= image_tag('shingeki.jpg', alt: 'shingeki.jpg', class: 'img-carousel d-block w-80') %>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="title-carouselle"><%= link_to "L'attaque des titans", anime_path(Anime.find_by_title("L'attaque des titans")), class:'remove-decoration' %></h1>
        </div>
      </div>
      <div class="carousel-item active">
        <%= image_tag('jujutsu_kaisen.png', alt: 'jujutsu_kaisen.png', class: 'img-carousel d-block w-80') %>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="title-carouselle"><%= link_to "Jujutsu Kaisen", anime_path(Anime.find_by_title("Jujutsu kaisen")), class:'remove-decoration' %></h1>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag('my_hero.png', alt: 'my_hero.png', class: 'img-carousel d-block w-80')%>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="title-carouselle"><%= link_to "My Hero Academia", anime_path(Anime.find_by_title("My hero academia")), class:'remove-decoration' %></h1>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag('fire_force.png', alt: 'fire_force.png', class: 'img-carousel d-block w-80')%>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="title-carouselle"><%= link_to "Fire Force", anime_path(Anime.find_by_title("Fire force")), class:'remove-decoration' %></h1>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag('black_clover.jpg', alt: 'black_clover.jpg', class: 'img-carousel d-block w-80')%>
        <div class="carousel-caption d-none d-md-block">
          <h1 class="title-carouselle"><%= link_to "Black Clover", anime_path(Anime.find_by_title("Black Clover")), class:'remove-decoration' %></h1>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="font-family">
  <div class="copyright form-inline">
    <p class="text-secondary">© 2021 Copyright: <span class="color-link">LaPassion.com</span></p>
  </div>
  <div class="social-media form-inline">
    <p class="text-secondary">Suivez-nous</p>
    <p class="color-link"><i class="fab fa-facebook"></i></p>
    <p class="color-link"><i class="fab fa-twitter"></i></p>
    <p class="color-link"><i class="fab fa-google-plus-g"></i></p>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="toggle">
    <i class="fas fa-bars"></i>
  </div>
  <ul class="menu">
    <li><%= link_to "ACCUEIL", "/", class: "menu_link" %></li>
    <% if current_user != nil %>
      <li><%= link_to "MA WATCHLIST", user_path(current_user), class: "menu_link" %></li>
    <% end %>
    <li><%= link_to "CATALOGUE", animes_path, class: "menu_link" %></li>
    <li><%= link_to "NOUVEAUTÉ", "", class: "menu_link" %></li>
    <li><%= link_to "ACTUALITÉ", "", class: "menu_link" %></li>
    <li><%= link_to "COMMUNAUTÉ", "", class: "menu_link" %></li>
  </ul>
  <%= link_to root_path, class: "logo-navbar" do%>
    <%= image_tag 'logo.png', class:"img-logo" %>
  <% end %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown hello-text">Bonjour <%= current_user.nickname %></li>
        <li class="nav-item dropdown">
          <%= image_tag "quentin.png", class: "goku avatar dropdown-toggle", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item", style: "color: $orange" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
<div class="overlay"></div>

app/views/shared/_searchbar.html.erb
<%= form_tag animes_path, method: :get do %>
  <%= text_field_tag :query,
    params[:query],
    class: "searchInput",
    placeholder: "Trouvez votre animé"
  %>
  <div class="searchIcon"></div>
<% end %>

app/views/users/show.html.erb
<div class="user_show_container">
  <div class="user_information">
    <%= image_tag "quentin.png", class: "avatar avatar_show_user" %>
    <p class="nickname_user_show_user"><%= @user.nickname %></p>
    <%= link_to 'Modifier votre profil', edit_user_registration_path, class: "btn_user_show_modify btn btn-warning btn-lg" %>
    <div class="my-subscription">
      <h5 class="mb-3
       text-center">Mes abonnements</h5>
      <div class="d-flex justify-content-around mb-2">
        <%= image_tag "wakanim_logo.png", style: 'height:10vh'%>
        <%= image_tag "crunchyroll_logo.png", style: 'height:10vh'%>
      </div>
    </div>
  </div>
  <div class="watchlist_show_user">
    <h1 class="title_header_user_show">MA WATCHLIST</h1>
    <div class="card-grid-container">
      <% @watchlist.each do |watchlist_anime| %>
        <div class="card m-4">
          <a href="<%= anime_path(watchlist_anime.anime) %>">
            <div class="cards-img-container">
              <%= cl_image_tag watchlist_anime.anime.photo.key, class: "card-img" %>
            </div>
            <div class="card-description">
              <h1 class="title-card"><%= watchlist_anime.anime.title %></h1>
            </a>
            <div class="like-btn">
              <% if current_user != nil %>
                <%= link_to watchlist_anime_path(watchlist_anime), method: :delete do%>
                  <div class="like" data-like-state="1"></div>
                <% end %>
              <% end %>
            </div>
            <p class="category"><%= watchlist_anime.anime.category %></p>
            <p class="rating">
              <% watchlist_anime.anime.rating.times do  %>
                <i class="fas fa-star"></i>
              <% end %>
              <% watchlist_anime.anime.blank_stars.times do %>
                <i class="far fa-star"></i>
              <% end %>
              (<%= watchlist_anime.anime.vote %> votes)
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>